name: online_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  auto_route: ^8.2.0
  bloc: ^8.1.4
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  pull_to_refresh: 
    git:
      url: https://github.com/anjarnaufals/flutter_pulltorefresh
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  auto_route_generator: ^8.0.0


flutter:
  assets:
    - assets/data.json
  uses-material-design: true
